version: '3.1'

services:

  db:
    image: postgis/postgis
    restart: always
    ports:
     - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
    volumes:
     - db:/var/lib/postgresql/data


  fe: 
    image: ghcr.io/mopped-hackers/fe-hk23:latest
    ports:
     - 80:80
    restart: always

  api:
    image: ghcr.io/mopped-hackers/be-api-hk23:latest
    restart: always
    ports:
      - 8000:8000
    environment:
      DEV_SQL_STRING: postgresql://postgres:password@vps.andrejvysny.sk/postgres
      PROD_SQL_STRING: postgresql://postgres:password@vps.andrejvysny.sk/postgres
      LOG_CONFIG_FILENAME: logging_config.yaml
    

volumes:
   db:
